[app]
primary_region = "iad"

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512

[processes]
app = "python -m uvicorn app:app --host 0.0.0.0 --port 8000"
